window.qsimTalks = {
  "Velocity-enabled control in metastable strontium arrays": {
    "authors": "Johannes Zeiher",
    "abstract": "Abstract not available."
  },
  "Observing strong-to-weak spontaneous symmetry breaking in a cold-atom quantum simulator": {
    "authors": "Dorothee Tell, Si Wang, Johannes Obermeyer, Marnix Barendregt, Petar Bojović, Thomas G. Kiely, Matthew P. A. Fisher, Abhijat Sarma, Philipp M. Preiss, Titus Franz, Cenke Xu and Immanuel Bloch",
    "abstract": "Analog quantum simulators with ultracold atoms in optical lattices have proven to be useful both for tests of fundamental quantum mechanics and for understanding the properties of materials with strongly correlated quantum states.\n\nIn this work we use them to make the first experimental observation of strong-to-weak spontaneous symmetry breaking (SW-SSB) which has recently attracted surging interest for the characterization of out-of-equilibrium mixed quantum states. By using the measurement process in a quantum gas microscope as an infinite-strength dephasing channel, we demonstrate the hallmark of SW-SSB: long-range order in Rényi-k correlators nonlinear in the density matrix. We show an analogy to off-diagonal long-range order in ordinary spontaneous symmetry breaking.\n\nMaking use of our 2D superlattice structure, we can tune the lattice from a homogeneous potential with random occupation to a deterministic crystal structure. This reveals the transition from the SW-SSB phase to strong symmetry.\n\nThese results open several avenues for future investigations on the nature of the SW-SSB transition and the analysis of further, more complex quantum states in this framework, e.g. to probe Choi-spin liquids with emergent gauge structure."
  },
  "Observation of a Dicke model in a two-dimensional ion crystal: chaos, quantum thermalization, and revivals": {
    "authors": "Sean Muleady, Bryce Bullock, Yicheng Zhang, Jennifer Lilieholm, Arghavan Safavi-Naini, Robert Lewis-Swan, John Bollinger, Ana Maria Rey and Allison Carter",
    "abstract": "Quantum many-body systems driven far from equilibrium can exhibit chaos, entanglement, and non-classical correlations, yet directly observing these phenomena in large, closed quantum systems remains challenging. Here we realize the Dicke model—a fundamental description of light-matter interactions—in a two-dimensional crystal of approximately 100 trapped ions. The ions’ internal state is optically coupled to the center of mass vibrational mode via an optical spin-dependent force, enabling unitary many-body dynamics beyond the mean-field and few-body limits. In the integrable regime, where the phonons can be adiabatically eliminated, we observe a dynamical phase transition between ferromagnetic to paramagnetic spin phases. In contrast, when the spins and phonons are strongly coupled, we observe clear signatures of non-integrable chaotic dynamics, including er- ratic phase-space trajectories and the exponential growth of excitations and entanglement quantified by the one-body Rényi entropy. By quenching from an unstable fixed point in the near-integrable regime, quantum noise can generate correlated spin-phonon excitations. Our numerical calculations, in clear agreement with experiment, reveal the generation of two-mode spin-phonon squeezing, 2.6 dB below the standard quantum limit (4.6 dB relative to the initial thermal state), followed by generalized vacuum Rabi collapses and revivals. Our results establish large ion crystals as scalable analog quantum simulators of non-equilibrium light-matter dynamics and provide a controlled platform for experimental studies of information scrambling and entanglement in closed many-body systems."
  },
  "Universal Gates from Braiding and Fusing Anyons on Quantum Hardware": {
    "authors": "Chiu Fan Bowen Lo, Anasuya Lyons, Dan Gresh, Michael Mills, Peter E. Siegfried, Maxwell D. Urmey, Nathanan Tantivasadakarn, Henrik Dreyer, Ashvin Vishwanath, Ruben Verresen and Mohsin Iqbal",
    "abstract": "Topological quantum computation encodes quantum information in the internal fusion space of non-Abelian anyonic quasiparticles, whose braiding implements logical gates. This goes beyond Abelian topological order (TO) such as the toric code, as its anyons lack internal structure. However, the simplest non-Abelian generalizations of the toric code do not support universality via braiding alone. Here we demonstrate that such minimally non-Abelian TOs can be made universal by treating anyon fusion as a computational primitive. We prepare a 54-qubit TO wavefunction associated with the smallest non-Abelian group, $S_3$, on Quantinuum’s H2 quantum processor. This phase of matter exhibits cyclic anyon fusion rules, known to underpin universality, which we evidence by trapping a single non-Abelian anyon on the torus. We encode logical qutrits in the nonlocal fusion space of non-Abelian fluxes and, by combining an entangling braiding operation with anyon charge measurements, realize a universal topological gate set and read-out, which we further demonstrate by topologically preparing a magic state.\n\nThis work establishes $S_3$ TO as simple enough to be prepared efficiently, yet rich enough to enable universal topological quantum computation."
  },
  "HamLib and Beyond: Building a Library of Hamiltonians for Quantum Benchmarking": {
    "authors": "Katie Klymko",
    "abstract": "Abstract not available."
  },
  "Accurate simulation of large-scale Fermi-Hubbard model on a digital quantum processor": {
    "authors": "Gavin S. Hartnett, Khadijeh Sona Najafi, Aleksei Khindanov, Haoran Liao, Michael Schutzman, Michael R. Hush, Michael J. Biercuk and Yuval Baum",
    "abstract": "The Fermi-Hubbard model is a paradigmatic description of strongly correlated electrons, yet its non-equilibrium dynamics remain challenging for exact classical methods for system sizes relevant to experiment. Here, we report digital quantum simulation of the one-dimensional Fermi-Hubbard model on a superconducting quantum processor using an efficient \\emph{local tiling} qubit mapping that exploits the heavy-hexagonal processor connectivity to implement all Trotter gates with nearest-neighbour two-qubit operations. We simulate chains of up to $L = 60$ sites ($120$ qubits) for hopping times $t_{\\max} \\sim 6 (1/t_h)$, achieving accuracy quantitatively comparable to classical time-dependent variational principle (TDVP) simulations at bond dimension $\\chi = 2048$, while the $L=60$ TDVP remains unconverged at this bond dimension. We benchmark the relaxation from a N\\'{e}el initial state and directly observe spin-charge separation: the holon wavefront propagates at velocity $v_h \\approx 0.96\\,t_h$ and the spinon at $v_s \\approx 0.35\\,t_h$ at $U/t_h= 6$, giving a ratio $v_h/v_s \\approx 2.69$ consistent with Bethe ansatz predictions. These results establish digital quantum processors as a versatile and quantitatively accurate platform for fermionic many-body dynamics in regimes inaccessible to classical computation."
  },
  "Observation of quantum-field-theory dynamics on a spin-phonon quantum computer": {
    "authors": "Anton Than, Saurabh Kadam, Vinay Vikramaditya, Nhung Nguyen, Xingxin Liu, Zohreh Davoudi, Alaina Green and Norbert Linke",
    "abstract": "Simulation of quantum field theories is expected to be an area where quantum computers excel over classical methods. However, mapping bosonic degrees of freedom onto qubits necessitates a substantial encoding overhead and large gate depth. These issues can be bypassed with a hybrid qubit-boson quantum simulator by directly mapping the bosons onto the simulator’s bosonic register. We experimentally demonstrate this by using a trapped-ion platform to simulate a (1+1)-dimensional Yukawa model, which involves fermions interacting with a bosonic scalar field. By mapping the fermions onto the spin-based qubits and the scalar fields onto the bosonic motional modes, we successfully simulate a system in a regime where classical methods start to become challenging. Our results provide a path forward to quantum advantage with hybrid qubit-boson systems."
  },
  "Quantum Simulation with Trapped-Ion Qudits": {
    "authors": "Martin Ringbauer",
    "abstract": "Today’s quantum computers and simulators are overwhelmingly based on binary information encoding. Yet the physical systems we want to simulate with these devices are often not two-level systems. Emulating such multi-level or higher spin systems with qubits can quickly become very costly. I will discuss how using qudits, naturally supported by today’s quantum computing hardware allows for the native and much more efficient quantum simulation of a range of models, most notably in high-energy physics."
  },
  "Measurement-based simulation of lattice gauge theory dynamics with adaptive quantum circuits on a trapped-ion processor": {
    "authors": "Hiroki Sukeno, Enrico Rinaldi and Takuya Okuda",
    "abstract": "Quantum simulation of lattice gauge theory offers the prospect of accessing real-time dynamics and finite-density regimes beyond the reach of classical computation. Maintaining gauge invariance during dynamical evolution remains a central challenge, as errors can accumulate and drive the system outside the physical gauge sector, necessitating active suppression of gauge-violating errors. Mid-circuit measurement provides a natural mechanism for stabilizing gauge constraints, and their incorporation naturally lends itself to a measurement-based architecture. We construct measurement-based protocols to simulate real-time dynamics of lattice gauge theories and implement them on Quantinuum’s H2 trapped-ion quantum processor, where all-to-all entangling gates generate an efficient resource state reflecting the spacetime locality of the target field theory and adaptive measurements drive Hamiltonian evolution. We observe coherent evolutions of gauge-invariant observables and demonstrate enhanced protection of gauge symmetry in dynamical wave functions. Our results position adaptive measurement-based quantum circuits as a natural framework for gauge-invariant dynamics and open new prospects for advantages over non-adaptive quantum simulations."
  },
  "Hybrid Digital-Analog Quantum Simulation with Ultracold Fermions": {
    "authors": "Philipp Preiss",
    "abstract": "Abstract not available."
  },
  "Pseudogap at ultralow temperatures in a Fermi-Hubbard quantum simulator": {
    "authors": "Lev Kendrick, Anant Kale, Youqi Gang, Alexander Deters, Martin Lebrat, Aaron Young and Markus Greiner",
    "abstract": "The behavior of the doped Hubbard model at low temperatures is a central problem in modern condensed matter physics, with relevance to correlated materials such as cuprate superconductors. Despite extensive computational studies, many open questions remain on its low-temperature phase diagram, motivating its study through quantum simulation with ultracold fermionic atoms in optical lattices. Here, leveraging a recent several-fold reduction in experimental temperatures, we report the first direct experimental observation of the pseudogap metal in the Hubbard model. These measurements are enabled by a novel, efficient spectroscopic technique with which we resolve the opening of a partial gap, which we further correlate with a thermodynamic anomaly in the equation of state that emerges at low temperatures. These results partially characterize the pseudogap regime and hint at a link between the pseudogap and charge order. We further report ongoing measurements that probe this link, among other measurements of stripe-like tendencies in this regime of the Hubbard model."
  },
  "Randomized Sparsification of Commuting Unitaries": {
    "authors": "Richard Allen and Aram Harrow",
    "abstract": "Circuit compilation is a central challenge in quantum computing, since circuit size is limited by noise on near-term devices and by synthesis cost in fault-tolerant architectures. In this work, we develop a principled framework for approximately implementing products of commuting unitaries while minimizing circuit size. We formulate this as a constrained approximation problem, minimizing diamond norm approximation error subject to a cutoff on circuit size, and show that classical randomization can be used to outperform deterministic compilation in this setting. We derive a simple probabilistic unitary synthesis method, randomized sparsification, in which each commuting unitary is treated independently and is either kept exactly, omitted, or importance sampled according to its distance to identity. We prove that randomized sparsification is nearly optimal among all approximation schemes, and we further show that it can substantially outperform conventional compilation methods, attaining arbitrarily large polynomial advantage over the best deterministic approaches as well as existing randomized strategies like qDRIFT. Finally, we extend randomized sparsification to incorporate variable gate costs, making it naturally compatible with hardware-aware compilation in settings with restricted connectivity, device-dependent noise, or fault-tolerant synthesis overhead."
  },
  "How to represent bosons using qubits for quantum simulation": {
    "authors": "Barbara Terhal",
    "abstract": "Abstract not available."
  },
  "Theory and Architecture of Weak Transversal Gates": {
    "authors": "Nobuyuki Yoshioka, Alireza Seif, Peter Groszkowski, Andrew Cross and Ali Javadi-Abhari",
    "abstract": "We introduce a general framework for weak transversal gates—probabilistic implementation of logical unitaries realized by local physical unitaries—and demonstrate its wide impact in three applications: partial fault-tolerant architecture, short-depth state preparation, and magic state distillation. Our theoretical contribution is to prove the sufficient condition for a general Calderbank-Shor-Steane code to admit weak transversal gates, and present an efficient algorithm to determine the physical multi-qubit Pauli rotations. To demonstrate the practicality of weak transversal gates in near future, we propose a partially fault-tolerant Clifford+$\\phi$ architecture that implements in-place Pauli rotations via a repeat-until-success strategy. Phenomenological simulations indicate that a rotation of $0.003$ attains logical error of $9.5\\times10^{-5}$ on a surface code with $d=7$ at physical error rate of $p_{\\rm phys}=10^{-4}$, while avoiding the spacetime overheads of magic state factories, small angle synthesis, and routing. Resource estimation on surface and [[144,12,12]] bivariate bicycle codes for a Trotter-like circuit with $N=108$ logical qubits indicate runtime reductions of up to two orders of magnitude due relative to the conventional Clifford+T execution, due to natural parallelism of rotation gates. Looking ahead to longer terms, we consider state-preparation tasks allowing postselection. We show that weak transversal gadgets prepare high-level equatorial magic states with a substantially improved cost–accuracy tradeoff, achieving up to a $10^3$-fold reduction in spacetime cost for magic state of 10-th level of Clifford hierarchy on surface code of $d=11$. Furthermore, we integrate weak transversal gates into magic state distillation pipelines, reducing the logical error rate of level-1 distillation of $\\sqrt{T}$ state by up to a factor of 94 with small increase in spacetime cost. %Compared to the existing approach of that non-fault-tolerant state injection, our approach reduces the logical error rate of distilled $\\sqrt{T}$ state by factor of 94 with moderate 1.5-fold increase in the spacetime cost. This work opens a novel paradigm for non-Clifford operations beyond conventional transversal and factory-based approaches."
  },
  "Significantly cheaper fault-tolerant Trotterization by improved Clifford+T synthesis for small-angle rotations": {
    "authors": "Marius Bothe, Christoph Sunderhauf, Michael Witham, Earl Campbell and Nick Blunt",
    "abstract": "Clifford+T synthesis of rotation gates is an important routine in fault-tolerant quantum simulation. It is generally understood that, while Clifford+T synthesis is scalable, it has a high overhead of tens of T gates per rotation in practice, translating to high resource estimates for many fault-tolerant algorithms. However, these well-known results are angle-independent, and it may be possible to do much better for angle-dependent results. This is particularly important since many quantum simulation methods, such as Trotterization, are dominated by small-angle rotations. In this submission we present results from a detailed numerical and theoretical study of Clifford+T rotation synthesis for small angles, and demonstrate its significant impact on fault-tolerant quantum simulation. We do this by taking probability and quasi-probability mixtures of Clifford+T channels, building on the mixed diagonal and mixed fallback schemes of Kliuchnikov et al. [Quantum 7, 1208 (2023)]. We show that rotation channels can be implemented with an average T cost of O(θ^2/δ) in the small-θ limit, and returning to known O(log(1/δ)) results in the worst case. This dispels the widely-stated claim that Clifford+T rotation synthesis has a high cost independent of θ. We derive new θ-dependent formulas that can be used for resource estimation. As an application of our results, we show that the gate cost of Trotterization circuits compiled to a Clifford+T gate set is constant in the small Trotter step size limit, and reduced by significant factors even for large step sizes. This reduction is significant enough that the cost of fault-tolerant Trotterization for a variety of applications should be re-examined in light of these results."
  },
  "Observation of Improved Accuracy over Classical Sparse Ground-State Solvers using a Quantum Computer": {
    "authors": "William Kirby",
    "abstract": "Demonstrating quantum advantage over classical algorithms for ground state energy problems is an outstanding open problem in quantum computation. We experimentally demonstrate that a quantum algorithm can outperform classical selected configuration interaction (SCI) methods, a key family of techniques used in computational chemistry and condensed matter physics. We construct a class of local Hamiltonian problems with sparse ground states, and show that SCI fails to find the ground state of a 49-qubit instance. We then show that sample-based Krylov quantum diagonalization, run on an IBM Heron R3 processor, succeeds at the same task. While the problem is solvable classically using iterative solvers designed to target our Hamiltonian construction, this work resolves the question of whether a sample-based quantum diagonalization algorithm can outperform standard SCI heuristics."
  },
  "Resonant false vacuum decay in two dimensions on a 4000-qubit quantum annealer": {
    "authors": "Gregor Humar, Jean-Yves Desaules, Luka Pavešić, Marko Ljubotina, Zlatko Papić, Kristel Michielsen and Jaka Vodeb",
    "abstract": "False vacuum decay (FVD), the quantum transition from a metastable to a true vacuum configuration, is a central non-perturbative phenomenon in quantum field theory and non-equilibrium statistical mechanics. Conventionally, FVD is described as a two-stage process: the semiclassical nucleation of a critical bubble followed by deterministic real-time expansion. However, its intrinsically non-perturbative nature and limited experimental accessibility have left key aspects of nucleation, propagation, and bubble interactions only partially understood. Building on previous studies of one-dimensional tilted Ising chains, we investigate FVD in the two-dimensional quantum Ising model and identify a distinct dynamical regime where nucleation and growth are intrinsically intertwined and governed by local resonance conditions. Using a programmable quantum annealer with more than 4000 qubits, we realize a metastable polarized state representing a false vacuum. At a tunable resonance in the longitudinal field, single-spin flips at the interface of a seeded true-vacuum bubble become energy-conserving. This enables a kinetically constrained, resonant expansion where the energy cost of domain-wall creation is compensated by the energy gain of the true vacuum, leading to non-trivial, fractal-like growth. By combining experimental measurements with tensor-network simulations and large-scale stochastic circuit modeling, we observe robust ballistic propagation of the true-vacuum wavefront across all approaches, persisting even in the presence of dissipation and disorder. Furthermore, the propagating interface exhibits sub-ballistic broadening with scaling behavior consistent with the Kardar-Parisi-Zhang (KPZ) universality class, indicating that the coarse-grained dynamics are governed by interface fluctuations. Our results establish a kinetic regime of false vacuum decay beyond the standard paradigm, where resonance-driven dynamics replace the conventional separation between nucleation and growth. More broadly, this work demonstrates that large-scale quantum simulation provides a powerful platform for exploring non-equilibrium metastable dynamics relevant to quantum field theory, cosmology, and strongly correlated many-body systems."
  },
  "Quantum computation of molecular geometry via many-body nuclear spin echoes": {
    "authors": "Chongwei Zhang, Rodrigo G. Cortinas, Amir Karamlou, Nicholas Noll, Justin Provazza, Johannes Bausch, Sergey Shirobokov, Alec White, Martin Claassen, Suh Hyun Kang, Chandrasekhar Ramanathan, Xiao Mi, Christian Bengs, Ashok Ajoy, Zlatko K. Minev, Nicholas Rubin and Thomas E. O'Brien",
    "abstract": "Quantum-information-inspired experiments in nuclear magnetic resonance spectroscopy may yield a pathway towards determining molecular structure and properties that are otherwise challenging to learn. We measure out-of-time-ordered correlators (OTOCs) [1-4] on two organic molecules suspended in a nematic liquid crystal, and investigate the utility of this data in performing structural learning tasks. We use OTOC measurements to augment molecular dynamics models, and to correct for known approximations in the underlying force fields. We demonstrate the utility of OTOCs in these models by estimating the mean ortho-meta H-H distance of toluene and the mean dihedral angle of 3′,5′-dimethylbiphenyl, achieving similar accuracy and precision to independent spectroscopic measurements of both quantities. To ameliorate the apparent exponential classical cost of interpreting the above OTOC data, we simulate the molecular OTOCs on a Willow superconducting quantum processor, using AlphaEvolve-optimized [5] quantum circuits and arbitrary-angle fermionic simulation gates. We implement novel zero-noise extrapolation techniques based on the Pauli pathing model of operator dynamics [6], to repeat the learning experiments with root-mean-square error 0.05 over all circuits used. Our work highlights a computational protocol to interpret many-body echoes from nuclear magnetic systems using low resource quantum computation."
  },
  "Tensor network studies of SU(N) Heisenberg and Hubbard models": {
    "authors": "Philippe Corboz",
    "abstract": "SU(N)-symmetric fermions with N flavors (or colors) on a lattice have attracted increasing interest thanks to the possibility of realizing them experimentally with alkaline-earth atoms in optical lattices. Over the past decade, numerical studies of these systems in the strong-coupling limit at integer filling, effectively described by SU(N) Heisenberg models, have revealed a rich variety of states of matter, including color-ordered states, valence bond solids, and a quantum spin liquid. More recently, the focus has shifted to the more challenging SU(N) Hubbard models at integer filling, where enhanced charge fluctuations at intermediate coupling give rise to different types of ordered states.In this talk I will first provide an overview of results for various two-dimensional SU(N) Heisenberg models obtained using infinite projected entangled-pair states (iPEPS), supported by complementary methods. In the second part, I will present recent iPEPS results for the SU(3) Hubbard model at 1/3 filling on the honeycomb and square lattices. On the honeycomb lattice, the model exhibits a phase transition between a plaquette valence-bond-solid state and a dimerized color-ordered state. On the square lattice at intermediate coupling strength, we find color-ordered states with a zigzag pattern, in agreement with other recent predictions. These results may provide useful predictions and benchmarks for future quantum simulators of SU(N) fermions."
  },
  "Quantum Simulation of Quantum Chromodynamics": {
    "authors": "Carter Gustin, William Simon, Kamil Serafin, Gary Goldstein and Peter Love",
    "abstract": "Quantum Chromodynamics (QCD) is the leading framework for describing bound states of quarks and gluons — hadrons — in the Standard Model. A central problem in high energy particle and nuclear physics is the calculation of hadronic bound state masses and wavefunctions. High-precision calculations of QCD are critical for analyzing collider physics data, which can lead to the discovery of new physics. In this work, we propose an end-to-end framework for quantum simulation of QCD, built on two pieces of foundational work — Ladder Operator Block Encoding (LOBE), and the Renormalization Group Procedure for Effective Particles (RGPEP). Notably, in this framework, observables measured with quantum phase estimation correspond to experimentally verifiable measurements."
  },
  "Quasiparticle quantum simulation: a framework for robust quantum advantage across electronic structure theory and dynamics": {
    "authors": "Garnet Chan",
    "abstract": "Most approaches to seeking quantum advantage in chemistry and materials applications require fine-tuning real-world applications to find instances where classical algorithms may struggle. I will describe a different strategy, where we seek quantum advantage in the domains where classical heuristics currently apply. In particular, we show that under the same structural assumptions used by classical heuristics for realistic electronic structure and dynamics problems, quantum algorithms achieve large polynomial advantages relative to classical heuristics, as well as over quantum algorithms which do not use these assumptions."
  },
  "Verifiable Quantum Advantage via Optimized DQI Circuits": {
    "authors": "Tanuj Khattar, Noah Shutty, Craig Gidney, Adam Zalcman, Nour Yosri, Dmitri Maslov, Ryan Babbush and Stephen P. Jordan",
    "abstract": "Recently, a quantum algorithm called Decoded Quantum Interferometry (DQI) was introduced that achieves an apparent exponential speedup for Optimal Polynomial Intersection (OPI) problem, which has previously been studied in the contexts of cryptography and error correcting codes. However, this left open the question of how many logical gates and logical qubits would be needed to solve a classically intractable instance of OPI. Here, we develop optimized implementations of DQI which greatly reduce its resource requirements. We establish that DQI for OPI is the first known candidate for verifiable quantum advantage with optimal asymptotic speedup: solving instances with classical hardness $O(2^N)$ requires only $\\widetilde{O}(N)$ quantum gates, matching the theoretical lower bound. To realize this, we overcome the primary bottleneck of reversible Reed-Solomon decoding by introducing novel quantum circuits for the Extended Euclidean Algorithm (EEA) that reduce the leading-order space complexity to the theoretical minimum of $2nb$ qubits. These improvements are broadly applicable, including to Shor’s algorithm for the discrete logarithm. We analyze OPI over binary extension fields $\\GF(2^b)$, assess hardness against new classical attacks, and identify resilient instances. Our resource estimates show that classically intractable OPI instances (requiring $>10^{23}$ classical trials) can be solved with approximately 5.72 million Toffoli gates. This is roughly $1000$ times fewer gates than required for factoring RSA-2048 and, remarkably, is also less than the leading interactive protocol for computational proof of quantumness, positioning DQI as a compelling candidate for practical, verifiable quantum advantage."
  },
  "Phase estimation with partially randomized time evolution": {
    "authors": "Jakob Günther, Freek Witteveen, Alexander Schmidhuber, Marek Miller, Matthias Christandl and Aram Harrow",
    "abstract": "Quantum phase estimation combined with Hamiltonian simulation is the most promising algorithmic framework to computing ground state energies on quantum computers. Its main computational overhead derives from the Hamiltonian simulation subroutine. In this paper we use randomization to speed up product formulas, one of the standard approaches to Hamiltonian simulation. We propose new partially randomized Hamiltonian simulation methods in which some terms are kept deterministically and others are randomly sampled. We perform a detailed resource estimate for single-ancilla phase estimation using partially randomized product formulas for benchmark systems in quantum chemistry and obtain orders-of-magnitude improvements compared to other simulations based on product formulas. When applied to the hydrogen chain, we have numerical evidence that our methods exhibit asymptotic scaling with the system size that is competitive with the best known qubitization approaches."
  },
  "Decoded Quantum Sensing with Dipolar and Cavity-Coupled Spins": {
    "authors": "Monika Schleier-Smith",
    "abstract": "Abstract not available."
  },
  "Quantum Advantage for Dynamical Phase Transition": {
    "authors": "Jue Xu, Xiao Yuan and Qi Zhao",
    "abstract": "Dynamical quantum phase transitions (DQPTs)—nonanalyticities of quantum dynamicsare a fundamental universality of nonequilibrium quantum matter, yet their computational complexity has not been systematically studied. We provide a complete complexity-theoretic classification: estimating the global rate function is GapP-hard, requiring exponential resources even for quantum computers, while determining a local (subsystem) DQPT is BQPcomplete, implying a provable quantum advantage. To search critical times of local DQPT in a given time range, we construct a nearly optimal algorithm that estimates the evolved observables at M time points with total simulation time \\tilde{O}(\\sqrt{M}T/ε) and prove a matching Ω(\\sqrt{M}/ε) lower bound. We further show that the critical time and universal scaling exponent are robust to algorithmic error and circuit noise. Our coherent multi-time-point estimation framework extends beyond DQPT to classical dynamics encoded in Hamiltonian evolution, providing wide applications of this quantum speedup. Together, these results establish local-DQPT detection as a practically accessible, provably hard, and optimally solvable quantum simulation advantage problem."
  },
  "Near-Term Quantum Simulation Algorithms for the Dynamics of Open Quantum Systems": {
    "authors": "Huan-Yu Liu, Tai-Ping Sun, Zhao-Yun Chen, Cheng Xue, Chao Wang, Xi-Ning Zhuang, Ming Gong, Jin-Peng Liu, Wei Yi, Yu-Chun Wu and Guo-Ping Guo",
    "abstract": "Open quantum systems exhibit a wide range of physically significant phenomena, yet their simulation remains challenging due to the exponential scaling of the Hilbert space and the intrinsically non-unitary nature of their dynamics. While numerous approaches have been proposed, few are compatible with the constraints of near-term quantum hardware. To address this issue, we develop several algorithms for simulating many-body dissipative dynamics on near-term quantum devices. First, we show that for a broad class of dissipation channels, Lindbladian dynamics can be mapped to a mixed-unitary adjoint channel, enabling direct implementation using unitary circuits. Second, we introduce a contour-based matrix decomposition technique that represents non-unitary evolution as a linear combination of unitary operations, achieving optimal complexity compared to existing LCHS-based methods. Third, we propose a variational quantum algorithm for simulating non-Hermitian dynamics, significantly reducing circuit depth and hardware overhead. These results advance the feasibility of simulating realistic open-system dynamics on near-term quantum processors and provide practical tools for quantum simulation in the NISQ era."
  },
  "Taming Trotter Errors with Quantum Resources": {
    "authors": "Xiangran Zhang, Jue Xu, Qi Zhao and You Zhou",
    "abstract": "Quantum simulation is a cornerstone application of quantum computing, yet how fundamental quantum resources—entanglement and non-stabilizerness (“magic”)—shape simulation fidelity remains an open question. In this work, we establish a rigorous connection between these resources and the statistical behavior of algorithmic errors arising in Hamiltonian simulation based on the Trotter-Suzuki formula. By analyzing ensembles of states with fixed entanglement entropy or magic, we make two key discoveries: First, the variance of the Trotter error decreases with increasing entanglement entropy, indicating a stronger concentration of error for entangled states. Moreover, we find that the kurtosis of the error exhibits a negative linear dependence on magic, implying that states with high magic possess lighter-tailed error distributions and thus a reduced probability of large deviations. These findings reveal a subtle phenomenon: quantum resources that obstruct classical emulation may, paradoxically, enhance the intrinsic robustness of quantum simulation, highlighting a constructive interplay between complexity and stability in quantum computation."
  },
  "Physically-Motivated Guiding States for Local Hamiltonians": {
    "authors": "Gabriel Waite, Karl Lin, Samuel Elman and Michael Bremner",
    "abstract": "We study the computational complexity of the Guided Local Hamiltonian problem: given a local Hamiltonian H together with a classical description of a guiding state that has non-negligible overlap with the ground state of H, estimate the ground-state energy within inverse-polynomial precision. This setting captures real-world scenarios in quantum chemistry and many-body physics, where trial states derived from classical heuristics can be used to guide quantum algorithms. We identify families of physically-motivated guiding states for which the computational hardness of ground-state energy estimation persists in the guided setting. Extending prior results for semi-classical subset states, we prove BQP-hardness for classes including fixed-weight states, matrix product states, Gaussian states, and Fendley states. Our hardness results are obtained via refined Feynman-Kitaev circuit-to-Hamiltonian constructions that explicitly expose the structural role of the guiding state in the reduction. Complementing these results, we give a constructive proof of BQP containment when the guiding state admits a polynomial-size classical description, establishing BQP-completeness for the canonical formulation of the problem. Our results show that quantum advantage persists for the newly introduced state classes, and classical methods also remain viable when said guiding states admit appropriate descriptions. Together, our results identify a Goldilocks zone of guiding states that are efficiently preparable, succinctly described, and sample-query accessible, within which quantum advantage for ground-state estimation can be meaningfully assessed. We additionally formalise the Guided Fermi-Hubbard Hamiltonian problem and prove BQP-completeness on 2D square and triangular lattices, both with and without magnetic fields, when provided with an appropriate fermionic guiding state."
  },
  "Quantum algorithms for stochastic nonlinear differential equations": {
    "authors": "Sergey Bravyi",
    "abstract": "Abstract not available."
  },
  "Predicting quantum dynamics of 50+ qubits from matrix product states with limited bond dimension": {
    "authors": "Kostyantyn Kechedzhi",
    "abstract": "Classical simulation of a wave function of an out-of-equilibrium many-body system requires exponential resources. At the same time expectation values of local operators and correlation functions can often be computed with much fewer resources, as such computations may not require storing the full wave function. This is particularly true for thermalizing systems at sufficiently high energy densities. Nonetheless, constructing classical algorithms away from this high energy density limit has remained a challenge. In this presentation we describe a heuristic approach to accelerate the convergence of Matrix Product State (MPS) simulations of expectation values applicable in a broad range of energy densities. Using this technique, we simulated the dynamics of the two-dimensional Transverse-Field Ising Model (TFIM) and XY model. Our method predicts the dynamics of the TFIM order parameter for 50+ qubits from the low bond dimension of 4096 and requires a single A100 GPU [1]. We compared our simulations with the largest experimental data available in the literature, grid of TFIM [2]. [1] Mandra et al, arxiv:2511.23438 [2] Haghshenas et al arXiv:2503.20870"
  },
  "Faster quantum chemistry simulations on a quantum computer with improved tensor factorization and active volume compilation": {
    "authors": "Nikolaj Moll, Athena Caesura, Cristian L. Cortes, William Pol, Sukin Sim, Mark Steudtner, Gian-Luca Anselmetti, Matthias Degroote, Raffaele Santagati, Michael Streif and Christofer S. Tautermann",
    "abstract": "We present a full-stack approach for accelerating fault-tolerant quantum simulations of electronic structure, demonstrated for the pharmacologically relevant cytochrome P450 active space. Our method combines block-invariant symmetry-shifted tensor hypercontraction (BLISS-THC), Active Volume compilation for fusion-based photonic hardware, and optimized block-encoding circuits. For P450, BLISS-THC reduces the Hamiltonian 1-norm from 388.9 to 130.9 Hartree while halving the factorization rank from 320 to 160 for chemical accuracy. Together with architectural and circuit improvements, these advances yield a total runtime speedup of up to 476 times relative to a THC baseline. In a realistic error-suppression scenario, the projected runtime drops from nearly 26 hours to approximately 3 minutes on matched-footprint devices, outlining a concrete path toward practical quantum chemistry workflows for drug discovery."
  },
  "Utility-scale electronic structure with under 100k noisy qubits": {
    "authors": "Guang Hao Low",
    "abstract": "We present a quantum code implementable on a regular $2$D hex grid with an estimated encoding rate up to $4.5\\times$ of that of a rotated surface code patch using circuit-level noise in a one- and two-qubit $10^{-3}$ error uniform depolarizing model. Our approach is based on yoking a dense packing of surface code twist defects, enabled by new stabilizer measurement cycles with an optimal four layers of nearest-neighbor two-qubit gates, almost no distance-reducing hook errors, and efficient decoding. We demonstrate a space-efficient architecture for computing on densely packed logical qubits, including new padding-free lattice surgery protocols in an optimal bounding box of $2d^2$ data and measurement qubits per patch. Assuming a $1\\mu$s surface code cycle time and a $10\\mu$s reaction time, these developments enable chemically accurate ground state phase estimation of a broad class of `utility-scale’ electronic structure simulation problems such as the $108$ spin-orbital FeMoco-based nitrogen fixation catalyst in under a month with $89$k noisy superconducting qubits. We elucidate a Pareto frontier of space-time trade-offs and find a minimum physical quantum volume of $1.3$ mega-qubit-hours. These correspond to a $36\\times$ space and $6.6\\times$ spacetime improvement, respectively, over our previous state-of-the-art minimum-Toffoli resource estimates (Phys. Rev. X 15, 041016)."
  },
  "Quantum Algorithms for Heterogeneous PDEs: The Neutron Diffusion Eigenvalue Problem": {
    "authors": "Andrew Childs, Lincoln Johnston, Brian Kiedrowski, Mahathi Vempati and Jeffery Yu",
    "abstract": "We develop a hybrid classical-quantum algorithm to solve a type of linear reaction- diffusion equation, the neutron diffusion (generalized) k-eigenvalue problem that establishes nuclear criticality. The algorithm handles an equation with piecewise constant coefficients, describing a problem in a heterogeneous medium. We apply uniform finite elements and show that the quantum algorithm provides significant polynomial end-to-end speedup over its classical counterparts. This speedup leverages recent advances in quantum linear systems—fast inversion and quantum preconditioning—and uses Hamiltonian simulation as a subroutine. Our results suggest that quantum algorithms may provide speedups for heterogeneous PDEs, though the extent of this advantage over the fastest classical algorithm depends on the effectiveness of other classical approaches such as nonuniform or adaptive meshing for a given problem instance."
  },
  "Efficient quantum algorithm for linear matrix differential equations and applications to open quantum systems": {
    "authors": "Sophia Simon, Dominic Berry and Rolando Somma",
    "abstract": "We present an efficient quantum algorithm for solving linear matrix differential equations, with applications to the simulation of open quantum systems and beyond. For unitary or dissipative dynamics, the algorithm computes an entry of the solution matrix with query complexity \\widetilde{O}(L^2 /epsilon), where L involves the time integral of the norm of the evolution operator and epsilon is the error. This L is linear in the evolution time t for unitary dynamics and can be bounded by a constant for dissipative dynamics. Our result contrasts prior quantum approaches for differential equations that typically require exponential time for this problem due to the encoding in a quantum state, which can lead to exponentially small amplitudes. We demonstrate the utility of the algorithm through an end-to-end application, namely the simulation of quantum Langevin dynamics for non-interacting fermions, and comment on applications to other quantum and classical systems. We compare with classical algorithms and give evidence of significant polynomial quantum speedups for systems in a lattice, which become more pronounced for systems with long-range interactions, and are exponential in general. We also provide a lower bound of \\Omega(L^2/epsilon) for unitary or weakly dissipative dynamics that proves our algorithm is optimal up to logarithmic factors."
  },
  "Quantum information and simulation with dual-species Rydberg arrays": {
    "authors": "Alexander Impertro",
    "abstract": "A key challenge in scaling up quantum processors and simulators is the need to implement individual qubit control in a resource-efficient yet performant manner. Rydberg arrays consisting of two distinct atomic species are a particularly promising platform to achieve this goal, with independent addressing and readout transitions enabling selective qubit control as well as mid-circuit operations.\n\nHere, we present how such a dual-species architecture allows the execution of a broad class of quantum circuits using only simple global control. Formulated in the framework of quantum cellular automata, we leverage discrete pulse sequences based on high-fidelity interspecies-mediated gates to prepare Bell, GHZ and cluster states, which we can additionally grow into graph-like states with longer-range connectivity. Moreover, the versatile Rydberg interaction landscape provided by two atomic species opens up the possibility to perform long-range multi-qubit gates.\n\nTogether, these results showcase how dual-species processors enable a highly efficient use of control resources, enhance scalability and thus pave the way for the next generation of quantum information and simulation experiments."
  },
  "One-to-one quantum simulation of the low-dimensional frustrated quantum magnet TmMgGaO4 with 256 qubits": {
    "authors": "Lucas Leclerc, Sergi Julià-Farré, Gabriel Silva Freitas, Guillaume Villaret, Minseong Lee, Tiago Mendes-Santos, Constantin Dalyac, Antoine Browaeys and Alexandre Dauphin",
    "abstract": "Low-dimensional materials exhibit exotic properties due to enhanced quantum fluctuations, making the understanding of their microscopic origin central in condensed matter physics. Analogue quantum simulators offer a powerful approach for investigating these systems at the microscopic level, particularly in large-scale regimes where quantum entanglement limits classical numerical methods. To date, analogue simulators have largely focused on universal Hamiltonians rather than material-specific quantitative comparisons. Here we use a Rydberg-based quantum simulator to study the bulk-layered frustrated quantum magnet TmMgGaO$_4$. Magnetisation measurements obtained from the quantum simulator show excellent agreement with independent measurements performed in a magnetic laboratory facility, validating the proposed effective two-dimensional microscopic Hamiltonian. Building on this quantitative correspondence, we investigate on both platforms the antiferromagnetic phase transition. We further probe the role of quantum fluctuations via snapshot analysis, connecting our results to integrated inelastic neutron scattering data. Finally, we access, with the simulator, non-equilibrium dynamics on picosecond material timescales, including frequency response and thermalisation of observables."
  },
  "Unified Probe of Quantum Chaos and Ergodicity from Hamiltonian Learning": {
    "authors": "Nik Gjonbalaj, Christian Kokail, Susanne Yelin and Soonwon Choi",
    "abstract": "Developing measures of quantum ergodicity and chaos stands as a foundational task in the study of quantum many-body systems. In this work, we propose metrics for these effects based on Hamiltonian learning that unify multiple advantages of existing metrics. In particular, we show how ergodicity and chaos improve the robustness of Hamiltonian learning to small errors and furthermore demonstrate that this robustness can be used as a metric for such phenomena. We analytically and numerically show that our metrics not only distinguish between integrable and ergodic regimes in various spin chains but also quantify chaos and ergodicity, allowing us to locate regions of parameter space displaying maximal ergodicity and maximal sensitivity to local perturbations. Our approach not only provides conceptual ways to study quantum chaos and ergodicity but also presents viable experimental methods for quantum simulators."
  },
  "Nearly-optimal fermion routing without ancillas": {
    "authors": "Nathan Constantinides, Jeffery Yu, Dhruv Devulapalli, Ali Fahimniya, Luke Schaeffer, Michael Gullans, Andrew Childs, Alexander Schuckert and Alexey Gorshkov",
    "abstract": "Routing is the task of permuting qubits to parallelize quantum operations as much as possible, given constraints on the hardware geometry. When simulating fermions with qubits in the Jordan-Wigner encoding, a one-dimensional nearest-neighbor-connected geometry is effectively imposed on the system, independently of the underlying hardware, naively imposing an O(N) depth routing overhead. Recently, it was demonstrated that this overhead can be reduced to O(log N), using Θ(N) ancillary qubits and employing measurements and feedforward. However, it was unknown whether a similar result can be achieved without additional qubits and whether in principle, it could be further reduced to O(1) Here, we show that O(log^2 N) overhead is possible without ancillary qubits and measurement and feedforward. We also construct efficient mappings with O(log^2 N) depth between all product-preserving ternary tree fermionic encodings, thereby showing that fermion routing in any such encoding can be done efficiently. While these results assume all-to-all connectivity, they also imply upper bounds for fermion routing in devices with limited connectivity by multiplying the fermion routing depth by the worst-case qubit routing depth. Finally, we show an Ω(log N) depth lower bound for fermion routing in the absence of measurement or feedforward, showing that our protocol is tight up to a log factor, even with arbitrarily many ancillas. Our results show there is a depth separation between fermionic and qubit-only quantum computers and lay the foundation for obtaining separation results in more realistic connectivity settings."
  },
  "Optimal strategies for near-term simulation of fermionic systems with scalable local fermion-to-qubit mappings": {
    "authors": "Manuel Algaba, Miha Papič, Emiliano Godinez-Ramirez, Inés de Vega, Adrian Auer, Alessio Calzona and Fedor Šimkovic",
    "abstract": "In this work, we study how local encodings provide stabilizer symmetries and code distance that can be directly exploited to suppress noise in a physically meaningful subspace. We first introduce a general framework to construct local fermion-to-qubit encodings with arbitrarily scalable distance by embedding known mappings into topological-code architectures, yielding new families such as Ladder and Perforated Encodings while keeping stabilizer weights fixed. These encodings make it possible to systematically explore the trade-offs between locality, redundancy, circuit cost, and protection against errors in one and two dimensions. Building on this structure, we then develop Subspace Noise Tailoring, a mitigation method that combines symmetry verification with probabilistic error cancellation by cancelling only those errors that are invisible to the encoded subspace. Numerical simulations of Fermi–Hubbard dynamics show that this substantially improves the cost-bias trade-off relative to existing approaches and extends the reach of near-term quantum simulations to larger and deeper fermionic problems."
  },
  "Exploring Interacting Spin Physics with Molecular Tweezer Arrays": {
    "authors": "Lawrence Cheuk",
    "abstract": "Abstract not available."
  },
  "Singlet-triplet oscillations in trapped circular Rydberg atoms of strontium": {
    "authors": "Mathis Pepin",
    "abstract": "Circular Rydberg states of strontium are promising platforms for quantum technologies. They exhibit much longer lifetimes than laser-accessible Rydberg states and possess an optically active ionic core that can be manipulated with laser light. Here we demonstrate trapping of circular states in optical tweezers by exploiting the polarizability of the ionic core. We measure the lifetime of a n = 51 circular state and observe singlet-triplet spin oscillations arising from several effects, including vectorial light shifts from the tweezers, spin-orbit coupling associated with the Rydberg electron, and ultimately the difference in Landé g-factor between the ionic core and the Rydberg electron. The dynamics of the circular state directly provides the differential Landé g-factor between the Sr+ 5s1/2 ionic core electron and a nearly free electron, allowing us to measure a relative correction on the order of 10−5 by a simple spin measurement."
  },
  "Programmable quantum simulation of anharmonic dynamics": {
    "authors": "Cameron McGarry, Teerawat Chalermpusitarak, Kai Schwennicke, Frank Scuccimarra, Maverick Millican, Vassili Matsos, Christophe Valahu, Prachi Nagpal, Hon-Kwan Chan, Henry Nourse, Ivan Kassal and Ting Rei Tan",
    "abstract": "Continuous-variable–discrete-variable (CV–DV) quantum simulators offer a natural route to simulating bosonic dynamics relevant to many branches of physics and chemistry. However, programmable simulation of arbitrary dynamics is an outstanding challenge. In particular, simulating anharmonic dynamics, which is ubiquitous across the physical sciences, is difficult due to the highly harmonic nature of oscillators used in CV–DV simulators. Here, we experimentally demonstrate programmable CV–DV quantum simulation of anharmonic dynamics in a range of double-well potentials, implemented in a trapped-ion system. We synthesise the time-evolution operators using a bosonic-quantum-signal-processing subroutine, which allows the potential to be tuned between experiments by controlling classical experimental parameters. We observe coherent dynamics in various double-well potentials, where a wavepacket tunnels through the potential barrier, and we suppress this effect by programmatically introducing asymmetry."
  },
  "Quantum simulation with neutral atoms: from analog to digital": {
    "authors": "Alexandra Geim",
    "abstract": "Abstract not available."
  },
  "Detecting the length-scale of topological order with quantum simulators": {
    "authors": "Robert Ott, Lisa Bombieri, Giuliano Giudici and Hannes Pichler",
    "abstract": "Topologically ordered quantum matter exhibits intriguing long-range patterns of entanglement, which reveal themselves in subsystem entropies. However, measuring such entropies, which can be used to certify topological order, on large partitions is challenging and becomes practically unfeasible for large systems. Here we propose and investigate a novel protocol based on local adiabatic deformations of the Hamiltonian which extracts the universal features of long-range topological entanglement from measurements on small subsystems of finite size, trading an exponential number of measurements against a polynomial-time evolution. Our protocol is general and readily applicable to various quantum simulation architectures, and allows for an efficient extraction of the length scale on which quantum systems exhibit topological entanglement features."
  },
  "Adiabatic echo protocols for robust preparation of entangled many-body states": {
    "authors": "Zhongda Zeng, Giuliano Giudici, Aruku Senoo, Alexander Baumgärtner, Adam Kaufman and Hannes Pichler",
    "abstract": "Entangled many-body states are a key resource for quantum technologies, yet their preparation via analog control of interacting quantum systems is often hindered by experimental imperfections. In this work, we introduce and generalize the adiabatic echo protocol, a versatile framework for many-body state preparation that suppresses the effects of static perturbations. We show that this approach achieves robust and high-fidelity state preparation through dynamically engineered destructive interference, enabling the realization of Greenberger–Horne–Zeilinger states in both Ising chains and Rydberg systems, as well as quantum spin liquid states in Rydberg lattices. We further extend this framework to the preparation of critical many-body states, where enhanced sensitivity to perturbations poses additional challenges. We demonstrate that the adiabatic echo mechanism remains effective in these regimes, with applications including critical states in Ising and Potts models and U(1) quantum spin liquid phases. Our results establish a unified and practical strategy for the robust preparation of complex many-body states, spanning conventional ordered phases to critical and highly correlated regimes, in present-day quantum platforms."
  },
  "Quantum simulation of non-Markovian dynamical systems": {
    "authors": "Abtin Ameri, Arkopal Dutt and Hari Krovi",
    "abstract": "Existing quantum algorithms for simulating dynamical systems — from Hamiltonian simulation to linear and nonlinear differential equations solvers — simulate Markovian dynamics, in which the system’s future evolution depends solely on its current state. In this paper, we turn our attention to developing efficient quantum algorithms for non-Markovian systems. These are dynamical systems with memory, where the system’s future evolution depends on its past history. Specifically, we develop efficient algorithms for linear Volterra integro-differential equations (VIDEs) with a convolution memory kernel. Given efficient circuits for the inputs of the problem, our algorithms attain an exponential speedup in system size over existing classical algorithms. We develop an algorithm for general kernels, assuming that $\\mathcal M<1$, where $\\mathcal M$ is a parameter characterizing the ratio of the strength the memory term to the strength of the Markovian part of the dynamics. We also provide lower bounds for simulating systems with $\\mathcal M\\geq 1$, showing that the problem becomes intractable. By specializing to structured kernels, we develop improved algorithms — even for $\\mathcal M \\geq 1$ — by converting the VIDE into a larger set of ODEs — a process which we call Markovianization. As an application, we discuss the linear coarse-graining framework. Our work greatly expands the range of dynamical systems that quantum computers can simulate efficiently and opens up several research directions in the field of quantum algorithms for non-Markovian dynamical systems."
  },
  "Provable Quantum Speedups for Reaction-Rate Estimation in High-Dimensional Fokker-Planck Dynamics": {
    "authors": "Tyler Kharazi, Ahmad M. Alkadri, Kranthi K. Mandadapu and K. Birgitta Whaley",
    "abstract": "The Fokker-Planck equation models rare events across sciences, but its high-dimensional nature challenges classical computers. Quantum algorithms for such non-unitary dynamics often suffer from exponential {decay in} success probability. We introduce a quantum algorithm that overcomes this bottleneck for estimating reaction rates. Using a sum-of-squares representation, we develop a Gaussian linear combination of Hamiltonian simulations (Gaussian-LCHS) to represent the non-unitary propagator with $O\\left(\\sqrt{t\\|H\\|\\log(1/\\epsilon)}\\right)$ queries to its block encoding. Crucially, we pair this with {a} novel technique to directly estimate matrix elements without exponential decay. For $\\eta$ pairwise interacting particles discretized with $N$ plane waves per degree of freedom, we estimate reactive flux to error $\\epsilon$ using $\\widetilde{O}\\left((\\eta^{5/2}\\sqrt{t\\beta}\\alpha_V + \\eta^{3/2}\\sqrt{t/\\beta}N)/\\epsilon\\right)$ quantum gates, where $\\alpha_V = \\max_{r}|V'(r)/r|$. We further prove that under comparable worst-case analytical guarantees, the sharpest classical bounds for estimating reaction rates via simulation of the associated overdamped Langevin dynamics scale as $O(t\\eta^2 e^{\\Omega(\\eta)}/\\epsilon^4)$, yielding an exponential improvement in $\\eta$, a quartic speedup in $\\epsilon$, and quadratic speedup in the time horizon $t$. While classical algorithms may outperform these bounds in practice, this work demonstrates a rigorous route toward quantum advantage for high-dimensional dissipative dynamics."
  },
  "TBA": {
    "authors": "Tony Ransford",
    "abstract": "Abstract not available."
  }
};
